
package com.cookbook.tutorial.service;

import com.cookbook.tutorial.internal.service.CookBookDefaultBackEndImp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-01-02T12:37:42.486-03:00
 * Generated source version: 2.5.9
 * 
 */
 
public class MuleStoreServer {

    protected MuleStoreServer() throws Exception {
        System.out.println("Starting Server");
        MuleCookBookServiceImpl implementor = new MuleCookBookServiceImpl();
        implementor.setServiceDAL(new CookBookDefaultBackEndImp());
        String address = "http://localhost:9090/cook-book";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new MuleStoreServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(6 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
