
package org.mule.tools.devkit.cookbook.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-01-02T12:37:42.486-03:00
 * Generated source version: 2.5.9
 * 
 */
 
public class MuleStoreServer {

    protected MuleStoreServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new MuleCookBookServiceImpl();
        String address = "http://localhost:9090/IMuleStoreServicePort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new MuleStoreServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
