#%RAML 0.8
title: Mule Store
version: 1.0.0
baseUri: http://server/api/{version}
schemas:
- book: !include mule-store-book.schema
- author: !include mule-store-author.schema
traits:
- searchable:
    queryParameters:
      query:
        required: false
        description: The Query to be processed
      pageSize:
        required: false
        default:  5
        description: Page to retrieve
      page:
        required: false
        description: Current Page
resourceTypes:
- entity:
    description: Collection of available <<resourcePathName>> in Jukebox.
    get:
      description: Get a list of <<resourcePathName>>.
      is: [searchable]
      responses:
        200:
          body:
            application/json:
              example: !include <<exampleCollection>>
    post:
      description: Creates a <<resourcePathName|!singularize>>.
      responses:
        200:
          body:
            application/json:
              example: |
                <<exampleItem>>
- entity-item:
    description: Entity representing a <<resourcePathName|!singularize>>
    get:
      description: |
        Get the <<resourcePathName|!singularize>>
        with <<resourcePathName|!singularize>>Id =
        {<<resourcePathName|!singularize>>Id}
      responses:
        200:
          body:
            application/json:
              example: !include <<exampleItem>>
    put:
      description: | 
        Add a new <<resourcePathName|!singularize>>
      body:
        application/json:
          example: |
            <<exampleItem>>
      responses:
        200:
          body:
            application/json:
              example: |
                <<exampleItem>>
    delete:
      description: |
        Deletes a <<resourcePathName|!singularize>>.
      responses:
        200:
           body:
             application/json:
              example: |
                {"message": "<<resourcePathName|!singularize>> not found" }
- bulk-api:
    description: Handle multiple <<entityType>> in a single request
    post:
      description: Creates a list of books
      responses:
        200:
          body:
            application/json:
              example: !include mule-store-book-collection.sample
    put:
      description: Updates a list of book
      responses:
        200:
          body:
            application/json:
              example: !include mule-store-book-collection.sample
    delete:
      description: Deletes a list of books
      responses:
        200:
          body:
            application/json:
              example: !include mule-store-book-collection.sample
/authors:
  type:
    entity:
      exampleCollection: !include mule-store-book-collection.sample
      exampleItem: !include mule-store-book.sample
  /{id}:
    type:
      entity-item: 
        exampleItem: !include mule-store-book.sample
  /bulk:
    type:
      bulk-api: 
        entityType: authors
/books:
  type:
    entity:
      exampleCollection: !include mule-store-book-collection.sample
      exampleItem: !include mule-store-book.sample
  /{id}:
    type:
      entity-item: 
        exampleItem: !include mule-store-book.sample
  /bulk:
    type:
      bulk-api: 
        entityType: books
/sales:
  type:
    entity:
      exampleCollection: !include mule-store-book-collection.sample
      exampleItem: !include mule-store-book.sample
  /{id}:
    type:
      entity-item: 
        exampleItem: mule-store-book.sample