:mule: Mule Store

== Adding DataSense

=== What is it?

http://www.mulesoft.org/documentation/display/current/DataSense[DataSense] is a feature used to improve the user experience at design time when creating Mule applications.

If coded correctly, user will be able to take advantage of the messages metadata to facilitate application design. With this functionality, Anypoint(TM) Studio proactively acquires information about data, such as data type and structure, in order to prescribe how to accurately map or use data in your application.

Is feature that displays the metadata of the entities included in the service in a friendly manner. Although this feature is optional, Mule strongly recommends that you use DataSense in your connector much easier to use for end users.

=== How to implement it

==== My model is static

Lets take a look at the v1 of the {mule} entities.

We only have Author, Book and Sale entities.

==== My model is dynamic

Use v2 to generate a dynamic data sense to describe standard and custom entities using the operations provided by the API

==== Testing it

Show an unit test of DataSense.
Show how to test it in Studio.

=== Adding @Query

Use v2 and extend datasense to describe what can be queryable.
