=== Adding @Transformer

==== What is a @Transformer
Transformers convert message payloads to formats expected by their destinations. Mule ESB provides many standard transformers, which you configure using predefined elements and attributes in your Mule XML configuration file but sometimes is useful to build custom transformers.

Annotating a method with @Transformer signals the Mule DevKit to export this method functionality as a transformer. Transformers need to be declared in classes annotated with @Module or @Connector and many transformers can be declared in the one class. It is possible to declare transformers, message processors and message sources in the same class.
The @Transformer annotated method must follow certain rules:

* It must be static
* It must be public
* It must not return void
* It must not return java.lang.Object
* It must receive exactly one argument
* It must be inside a class annotated with @Connector

==== Creating a transformer

// TODO

From String Json representation to Entity

==== Using the transformer in a Mule app

// TODO

Show how it is used with auto discovery

Show how it is used explicitly

==== Test my @Transformer

// TODO